@hostname = localhost
@port = 7274
@host = {{hostname}}:{{port}}
@contentType = application/json


###
GET https://{{host}}/exercise HTTP/1.1

###
@exerciseId = 5a774fb7-b53c-4d69-9e7d-8bcf59978d34

GET https://{{host}}/exercise/{{exerciseId}} HTTP/1.1

###

# @prompt name
# @prompt description

PUT https://{{host}}/exercise HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "{{name}}",
    "description": "{{description}}",
    "tags": ["home", "gym"] 
}