@hostname = localhost
@port = 7274
@host = {{hostname}}:{{port}}
@contentType = application/json


###
GET https://{{host}}/exercise HTTP/1.1

###
@exerciseId = 2eafd7a2-8522-425a-932c-4d5675eeb1c8

GET https://{{host}}/exercise/{{exerciseId}} HTTP/1.1

###

# @prompt name
# @prompt description

PUT https://{{host}}/exercise HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "{{name}}",
    "description": "{{description}}",
    "tags": ["home", "gym"] 
}