@hostname = localhost
@port = 7274
@host = {{hostname}}:{{port}}
@contentType = application/json

@exerciseId = 7a3e7649-9e83-4cd0-b528-cbb92ff1b2b8

PUT https://{{host}}/planner/exercise HTTP/1.1
Content-Type: {{contentType}}

{
    "exerciseId": "{{exerciseId}}",
    "repetitions": "[
        {
            "count": 12,
            "unit": 2,
            "note": "test"
        }
    ]"
}

@plannerExerciseId = 50da3bc3-c4ef-44f6-bd9a-96bff0fe3fcb

@startTime = "2022-10-31"
@endTime = "2022-11-31"

PUT https://{{host}}/planner HTTP/1.1
Content-Type: {{contentType}}

{
    "startTime": "{{startTime}}",
    "endTime": "{{endTime}}"
}

@plannerId = cba2e49f-898f-4fe5-b331-bd242fe3d0a3