# A Docker Compose must always start with the version tag.
# We use '3' because it's the last version.
version: '3'

# You should know that Docker Compose works with services.
# 1 service = 1 container.
# For example, a service, a server, a client, a database...
# We use the keyword 'services' to start to create services.
services:
  personFit:
    image: personfit
    ports:
      - "8080:80"
    environment:
      postgres__Database: default_database
      postgres__Username: username
      postgres__Password: password
      postgres__Host: postgres
      isMigrate: true
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - "database"
    networks:
      - personFitNetwork

  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: yoursecretPassword123 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: keycloak # T
#    networks:
#      - personFitNetwork
#    hostname: postgres
      
networks:
  personFitNetwork: 