// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonFit.Domain.Planner.Infrastructure.Postgres;
using PersonFit.Domain.Planner.Infrastructure.Postgres.Documents;

#nullable disable

namespace PersonFit.Domain.Planner.Migrations
{
    [DbContext(typeof(PostgresPlannerDomainContext))]
    [Migration("20221026184254_PlannerInit")]
    partial class PlannerInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planner")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonFit.Domain.Planner.Infrastructure.Postgres.Documents.ExercisePlannerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<IEnumerable<RepetitionDao>>("Repetitions")
                        .HasColumnType("jsonb")
                        .HasColumnName("repetitions");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_planner_exercises");

                    b.ToTable("planner_exercises", "planner");
                });

            modelBuilder.Entity("PersonFit.Domain.Planner.Infrastructure.Postgres.Documents.PlannerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<IEnumerable<DailyPlannerDao>>("DailyPlanners")
                        .HasColumnType("jsonb")
                        .HasColumnName("daily_planners");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_planners");

                    b.ToTable("planners", "planner");
                });
#pragma warning restore 612, 618
        }
    }
}
